spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev #开发环境
  application:
    name: microsservicecloud-config-dev

---
spring:
  profiles: test #测试环境
  application:
    name: microsservicecloud-config-test

#保存UTF-8编码
