spring:
  profiles:
    active:
      - dev
---
server:
  port: 8001

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml     #mybatis 的配置路径
  type-aliases-package: cn.tx.springcloud.entities                      #entity别名类所在包
  mapper-locations: classpath:mybatis/mapper/*.xml      #mapper 映射文件


spring:
  profiles: dev
  application:
    name: microsservicecloud-config-dept-client #对外暴露的微服务名字
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  #当前数据库操作类型
    driver-class-name: com.mysql.jdbc.Driver #mysql驱动包
    url: jdbc:mysql://127.0.0.1:3306/cloudDB01    #url连接地址
    username: root
    password: root
    dbcp2:
      min-idle: 5           #连接池最小连接数
      initial-size: 5       #初始化连接数
      max-idle: 5           #连接池最大连接数
      max-wait-millis: 200  #等待连接获取的最大超时时间


eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/ #将客户端注册到eureka服务列表中
  instance:
    instance-id: microsservicecloud-dept8001 #自定义服务名称信息
    prefer-ip-address: true #访问路径可以显示ip 地址

info:
  app.name: cloud-microsservicecloud //写死的
  company.name: www.cloud.com
  build.artifactId: $project.artifactId$ //动态
  build.version: $project.version$
---
server:
  port: 8001

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml     #mybatis 的配置路径
  type-aliases-package: cn.tx.springcloud.entities                      #entity别名类所在包
  mapper-locations: classpath:mybatis/mapper/*.xml      #mapper 映射文件


spring:
  profiles: test
  application:
    name: microsservicecloud-config-dept-client #对外暴露的微服务名字
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  #当前数据库操作类型
    driver-class-name: com.mysql.jdbc.Driver #mysql驱动包
    url: jdbc:mysql://127.0.0.1:3306/cloudDB01    #url连接地址
    username: root
    password: root
    dbcp2:
      min-idle: 5           #连接池最小连接数
      initial-size: 5       #初始化连接数
      max-idle: 5           #连接池最大连接数
      max-wait-millis: 200  #等待连接获取的最大超时时间


eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: microsservicecloud-dept8001 #自定义服务名称信息
    prefer-ip-address: true #访问路径可以显示ip 地址

info:
  app.name: cloud-microsservicecloud //写死的
  company.name: www.cloud.com
  build.artifactId: $project.artifactId$ //动态
  build.version: $project.version$
