spring:
  profiles:
    active:
      - dev
---
server:
  port: 7001

spring:
  profiles: dev
  application:
    name:microsservice-config-eureka-client

eureka:
  instance:
    hostname: eureka7001.com #eureka服务端的实例名称
  client:
    register-with-eureka: false #表示不向注册中心注册自己,即 物业不需要给物业自己缴费
    fetch-registry: false #表示自己端就是注册中心,我的职责是维护网络实例,b并不需要检索服务,注册列表里不需要有我
    service-url:
      #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
      #相当于物业收取物业费的卡号
      defaultZone: http://eureka7001.com:7001/eureka/
---
server:
  port: 7001

spring:
  profiles: test
  application:
    name:microsservice-config-eureka-client


eureka:
  instance:
    hostname: eureka7001.com #eureka服务端的实例名称
  client:
    register-with-eureka: false #表示不向注册中心注册自己,即 物业不需要给物业自己缴费
    fetch-registry: false #表示自己端就是注册中心,我的职责是维护网络实例,b并不需要检索服务,注册列表里不需要有我
    service-url:
      #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
      #相当于物业收取物业费的卡号
      defaultZone: http://eureka7001.com:7001/eureka/
